export const SAMPLE_EVENT_DATA: Record<string, Record<string, unknown>> = {
  event: {
    eventType: 'Meeting',
    eventName: 'Q4 Sales Kickoff',
    guests: 26,
    agenda: 'AM plenary, PM breakouts; AV + Wi-Fi.',
    need_spaces: true,
    spaces_count: 3,
    need_catering: true,
    catering_needs_count: 3,
    need_housing: true,
    housing_need_count: 26,
    single_rooms_count: 26,
    need_activity: false,
    dates_flexible: true,
    dates_flexible_details: 'Prefer Oct 30, +/-2 days',
    eventFormat: 'meeting',
    status: 'tentative',
    status_external: 'New RFP!',
    status_internal: 'Qualified',
    hold_expires_at: '2025-10-07T12:00:00+02:00',
    timezone: 'Europe/Berlin',
    setup_minutes: 60,
    teardown_minutes: 45,
    confidentiality: 'standard',
    languages: ['en', 'de'],
    accessibility_requirements: {
      wheelchair_users: 1,
      hearing_loop: true,
      accessible_rooms_needed: 1,
    },
    channel: 'widget',
    source_name: 'Sales Opp',
    series_id: 'series-2025-q4',
  },
  budget: {
    budget_defined: true,
    currency: 'EUR',
    global_budget: 15000,
    tax_inclusive: true,
    category_caps: { fnb_max: 7000, av_max: 3000 },
  },
  'company-info': {
    organizer: {
      first_name: 'Samantha',
      last_name: 'Lee',
      email: 'samantha@example.com',
      phone: '+49 30 1234 5678',
      company_name: 'Acme GmbH',
    },
    internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' },
  },
  venue: {
    venue_id: 42,
    venue_name: 'Hotel Berlin Mitte',
  },
  location: {
    name: 'Hotel Berlin Mitte',
    address: 'Friedrichstr. 100, 10117 Berlin, Germany',
    lat: 52.5206,
    lng: 13.3862,
    locality: 'Berlin',
    zipcode: '10117',
    country: 'Germany',
    country_code: 'DE',
  },
  'meeting-room': {
    capacity: 120,
    dispositions: ['classroom', 'theater'],
    natural_light: true,
    seating: 'classroom',
    time_from: '08:00',
    time_to: '18:00',
    ceiling_height_m: 4.2,
    floor_area_sqm: 220,
    divisible: false,
    pillars: false,
    network: { dedicated_bandwidth_mbps: 200, hardline_ports: 6 },
  },
  'food-and-beverage': {
    abstract: 'AM/PM coffee + lunch',
    description: 'Buffet lunch; vegetarian and gluten-free options.',
    service_style: 'buffet',
    dayparts: ['coffee_break', 'lunch', 'pm_break'],
    dietary_counts: { vegetarian: 4, gluten_free: 2 },
    items: ['li_am_coffee', 'li_lunch', 'li_pm_coffee'],
  },
  equipment: {
    name: 'Projector',
    model: 'Epson EB-2250U',
    quantity: 2,
    connectors: ['HDMI', 'VGA'],
    operator_required: false,
    rental_type: 'in-house',
    catalog_id: 'res-28',
  },
  datetime: {
    from_date: '2025-10-30',
    from_hour: '08:00',
    to_date: '2025-10-30',
    to_hour: '18:00',
    timezone: 'Europe/Berlin',
  },
  source: {
    channel: 'widget',
    external_rfp_id: 'RFP-99821',
    tracking_id: 'trk-71f8b',
    owner: 'emma@hotel.example',
    is_mailbot: false,
    is_outlook_addin: false,
    is_quote_generator: false,
    lead_source_name: 'Sales Opp',
    supplier_id: 'SUP-1001',
    hotel_unique_id: 'BER-MITTE-42',
    portal_name: 'Emma Widget',
  },
  'conference-day': {
    date: '2025-10-30',
    persons: 26,
    timezone: 'Europe/Berlin',
    packages: ['pkg_01'],
    rooms: ['room_main', 'room_b1', 'room_b2'],
    equipment: ['li_wifi', 'li_projector_main'],
    remarks: 'Plenary AM, breakouts PM.',
  },
  package: {
    name: 'Requested Meeting Package',
    description: 'Includes AM/PM coffee, lunch, water, room rental',
    count: 26,
    calc_per: 'person',
    items: ['li_am_coffee', 'li_lunch', 'li_pm_coffee', 'li_water'],
  },
  'line-item': {
    catalog_id: 'res-33',
    title: 'Business Lunch',
    title_multilang: [
      { lang: 'en', value: 'Business Lunch' },
      { lang: 'de', value: 'Business-Lunch' },
    ],
    count: 26,
    time_from: '12:00',
    time_to: '13:00',
    price_unit: 'per person',
    included_in_package: true,
    notes: 'Vegetarian option required',
  },
  'room-block': {
    arrival_date: '2025-10-30',
    departure_date: '2025-10-31',
    cutoff_date: '2025-10-10',
    currency: 'EUR',
    rooms: [{ room_type: 'single', count: 26, rate: 145, breakfast_included: true }],
    attrition_percent: 10,
    remarks: 'Early check-in requested for 6 rooms.',
  },
  deadline: {
    offer_deadline: '2025-10-05T17:00:00+02:00',
    option_due_date: '2025-10-07T12:00:00+02:00',
    timeout_date: '2025-10-07T12:30:00+02:00',
    policy_check_results: [{ rule: 'min_lead_time_days', passed: true }],
    history: [{ at: '2025-09-25T16:20:00+02:00', by: 'system', change: 'Offer issued; 72h option.' }],
  },
  'policy-terms': {
    cancellation_terms: [
      { deadline: '2025-10-15T00:00:00+02:00', penalty_type: 'percent', penalty_value: 25 },
      { deadline: '2025-10-25T00:00:00+02:00', penalty_type: 'percent', penalty_value: 50 },
    ],
    deposit_terms: [
      { due_date: '2025-10-01', percent: 30 },
      { due_date: '2025-10-20', percent: 50 },
    ],
  },
  stats: {
    lead_time_days: 35,
    persons_total: 26,
    rooms_nights_total: 26,
    peak_day_persons: 26,
    generated_at: '2025-09-25T16:35:00+02:00',
    version: 'v1.0',
    details: { per_day: [{ date: '2025-10-30', persons: 26 }] },
  },
  content: {
    currency: 'EUR',
    process_overview: [
      { label: 'RFP received', at: '2025-09-24T09:15:00+02:00' },
      { label: 'Offer sent', at: '2025-09-25T11:30:00+02:00', status: 'Pending client' },
    ],
    attachments: [{ name: 'Floorplan Hall A.pdf', url: 'https://cdn.example/hall-a.pdf', mime: 'application/pdf' }],
    remarks: [
      { remark_type: 'MAIN', text: 'Quiet room preferred.', created_at: '2025-09-25T10:00:00+02:00' },
      { remark_type: 'LEGAL', text: 'DPA required.' },
    ],
  },
  'availability-check': {
    date: '2025-10-30',
    timezone: 'Europe/Berlin',
    is_calculated: true,
    event_date_available: true,
    alternate_date_available: true,
    capacity_confirmed: true,
    availability_confirmed: true,
    criteria: { pax: 26, seating: 'classroom', time_from: '08:00', time_to: '18:00' },
    matching_rooms: [
      { room_id: 'room_main', is_available: true },
      { room_id: 'room_b1', is_available: true },
    ],
    available_rooms_without_combinations: ['room_b2'],
  },
  'integration-log': {
    system: 'emma',
    operation: 'Create',
    request_at: '2025-09-25T16:31:00+02:00',
    response_at: '2025-09-25T16:31:01+02:00',
    http_status: 400,
    result_status: 'FAIL',
    error_code: '117',
    error_description: 'Invalid Event Lead Time',
    retryable: false,
    request_ref: 's3://intlog/evt_123/create.req.json',
    response_ref: 's3://intlog/evt_123/create.res.json',
  },
  misc: {
    email_html: '<p>Raw inbound...</p>',
    legacy_payload_ref: 's3://bucket/legacy/evt_123.json',
  },
};
