import type { VenueProfile } from './venue-data';
import { VENUES } from './venue-data';

export interface EventTemplate {
  name: string;
  venueIndex: number;
  event: Record<string, unknown>;
  budget: Record<string, unknown>;
  companyInfo: Record<string, unknown>;
  meetingRoom: Record<string, unknown>;
  fnb: Record<string, unknown>;
  equipment: Record<string, unknown>;
  datetime: Record<string, unknown>;
  conferenceDay: Record<string, unknown>;
  roomBlock: Record<string, unknown>;
  stats: Record<string, unknown>;
}

function buildComponents(tpl: EventTemplate, venue: VenueProfile): Record<string, Record<string, unknown>> {
  return {
    event: tpl.event,
    budget: tpl.budget,
    'company-info': tpl.companyInfo,
    venue: { venue_id: venue.venue_id, venue_name: venue.venue_name },
    location: {
      name: venue.venue_name,
      address: venue.address,
      lat: venue.lat,
      lng: venue.lng,
      locality: venue.locality,
      zipcode: venue.zipcode,
      country: venue.country,
      country_code: venue.country_code,
    },
    'meeting-room': tpl.meetingRoom,
    'food-and-beverage': tpl.fnb,
    equipment: tpl.equipment,
    datetime: tpl.datetime,
    source: {
      channel: 'widget',
      external_rfp_id: `RFP-${Math.floor(10000 + Math.random() * 89999)}`,
      tracking_id: `trk-${Math.random().toString(36).slice(2, 7)}`,
      owner: 'pm@hotel.example',
      is_mailbot: false,
      is_outlook_addin: false,
      is_quote_generator: false,
      lead_source_name: 'Direct',
      supplier_id: `SUP-${venue.venue_id}`,
      hotel_unique_id: venue.hotel_unique_id,
      portal_name: 'Booking Widget',
    },
    'conference-day': tpl.conferenceDay,
    package: {
      name: 'Day Delegate Package',
      description: 'Standard package with refreshments and lunch',
      count: (tpl.event as { guests: number }).guests,
      calc_per: 'person',
      items: ['li_coffee', 'li_lunch', 'li_water'],
    },
    'line-item': {
      catalog_id: 'res-50',
      title: 'Business Lunch',
      title_multilang: [
        { lang: 'en', value: 'Business Lunch' },
        { lang: 'de', value: 'Business-Lunch' },
      ],
      count: (tpl.event as { guests: number }).guests,
      time_from: '12:00',
      time_to: '13:00',
      price_unit: 'per person',
      included_in_package: true,
      notes: '',
    },
    'room-block': tpl.roomBlock,
    deadline: {
      offer_deadline: `${(tpl.datetime as { from_date: string }).from_date.slice(0, 7)}-01T17:00:00+02:00`,
      option_due_date: `${(tpl.datetime as { from_date: string }).from_date.slice(0, 7)}-05T12:00:00+02:00`,
      timeout_date: null,
      policy_check_results: [{ rule: 'min_lead_time_days', passed: true }],
      history: [],
    },
    'policy-terms': {
      cancellation_terms: [
        { deadline: `${(tpl.datetime as { from_date: string }).from_date}T00:00:00+02:00`, penalty_type: 'percent', penalty_value: 50 },
      ],
      deposit_terms: [
        { due_date: `${(tpl.datetime as { from_date: string }).from_date.slice(0, 7)}-01`, percent: 30 },
      ],
    },
    stats: tpl.stats,
    content: {
      currency: 'EUR',
      process_overview: [
        { label: 'RFP received', at: new Date().toISOString() },
      ],
      attachments: [],
      remarks: [],
    },
    'availability-check': {
      date: (tpl.datetime as { from_date: string }).from_date,
      timezone: 'Europe/Berlin',
      is_calculated: true,
      event_date_available: true,
      alternate_date_available: false,
      capacity_confirmed: true,
      availability_confirmed: true,
      criteria: {
        pax: (tpl.event as { guests: number }).guests,
        seating: (tpl.meetingRoom as { seating: string }).seating || 'theater',
        time_from: '08:00',
        time_to: '18:00',
      },
      matching_rooms: [{ room_id: 'room_main', is_available: true }],
      available_rooms_without_combinations: [],
    },
    'integration-log': {
      system: 'pms',
      operation: 'Create',
      request_at: new Date().toISOString(),
      response_at: new Date().toISOString(),
      http_status: 200,
      result_status: 'SUCCESS',
      error_code: null,
      error_description: null,
      retryable: false,
      request_ref: '',
      response_ref: '',
    },
    misc: {},
  };
}

const TEMPLATES: EventTemplate[] = [
  // ── Hotel Berlin Mitte (venue 0) ── 7 events
  {
    name: 'Q4 Sales Kickoff',
    venueIndex: 0,
    event: { eventType: 'Meeting', eventName: 'Q4 Sales Kickoff', guests: 26, agenda: 'AM plenary, PM breakouts', need_spaces: true, spaces_count: 3, need_catering: true, catering_needs_count: 3, need_housing: true, housing_need_count: 26, single_rooms_count: 26, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 60, teardown_minutes: 45, confidentiality: 'standard', languages: ['en', 'de'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 15000, tax_inclusive: true, category_caps: { fnb_max: 7000, av_max: 3000 } },
    companyInfo: { organizer: { first_name: 'Samantha', last_name: 'Lee', email: 'samantha@acme.de', phone: '+49 30 1234 5678', company_name: 'Acme GmbH' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 120, dispositions: ['classroom', 'theater'], natural_light: true, seating: 'classroom', time_from: '08:00', time_to: '18:00', ceiling_height_m: 4.2, floor_area_sqm: 220, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 6 } },
    fnb: { abstract: 'AM/PM coffee + lunch', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 4, gluten_free: 2 }, items: ['li_am_coffee', 'li_lunch', 'li_pm_coffee'] },
    equipment: { name: 'Projector', model: 'Epson EB-2250U', quantity: 2, connectors: ['HDMI', 'VGA'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-28' },
    datetime: { from_date: '2025-10-30', from_hour: '08:00', to_date: '2025-10-30', to_hour: '18:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-30', persons: 26, timezone: 'Europe/Berlin', packages: ['pkg_01'], rooms: ['room_main', 'room_b1'], equipment: ['li_projector'], remarks: 'Plenary AM, breakouts PM' },
    roomBlock: { arrival_date: '2025-10-30', departure_date: '2025-10-31', cutoff_date: '2025-10-10', currency: 'EUR', rooms: [{ room_type: 'single', count: 26, rate: 145, breakfast_included: true }], attrition_percent: 10 },
    stats: { lead_time_days: 35, persons_total: 26, rooms_nights_total: 26, peak_day_persons: 26, generated_at: '2025-09-25T16:35:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-30', persons: 26 }] } },
  },
  {
    name: 'Annual Tech Summit 2025',
    venueIndex: 0,
    event: { eventType: 'Conference', eventName: 'Annual Tech Summit 2025', guests: 180, agenda: '3-day conference with keynotes and workshops', need_spaces: true, spaces_count: 8, need_catering: true, catering_needs_count: 6, need_housing: true, housing_need_count: 160, single_rooms_count: 140, need_activity: true, dates_flexible: false, eventFormat: 'conference', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 180, teardown_minutes: 120, confidentiality: 'standard', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 78000, tax_inclusive: true, category_caps: { fnb_max: 32000, av_max: 15000, space_max: 12000, rooms_max: 19000 } },
    companyInfo: { organizer: { first_name: 'Marcus', last_name: 'Weber', email: 'marcus@techcorp.eu', phone: '+49 30 9876 5432', company_name: 'TechCorp EU' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 250, dispositions: ['theater', 'classroom'], natural_light: true, seating: 'theater', time_from: '07:30', time_to: '20:00', ceiling_height_m: 5.5, floor_area_sqm: 420, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 500, hardline_ports: 12 } },
    fnb: { abstract: 'Full-day catering for 3 days', service_style: 'buffet', dayparts: ['breakfast', 'coffee_break', 'lunch', 'pm_break', 'reception'], dietary_counts: { vegetarian: 30, vegan: 12, gluten_free: 8, halal: 5 }, items: ['li_breakfast', 'li_coffee', 'li_lunch', 'li_pm', 'li_reception'] },
    equipment: { name: 'AV Package', model: 'Full Conference Setup', quantity: 1, connectors: ['HDMI', 'SDI', 'USB-C'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-av-full' },
    datetime: { from_date: '2025-11-12', from_hour: '07:30', to_date: '2025-11-14', to_hour: '18:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-12', persons: 180, timezone: 'Europe/Berlin', packages: ['pkg_conf'], rooms: ['ballroom', 'ws_1', 'ws_2', 'ws_3'], equipment: ['li_av_full'], remarks: 'Keynote Day 1' },
    roomBlock: { arrival_date: '2025-11-11', departure_date: '2025-11-15', cutoff_date: '2025-10-20', currency: 'EUR', rooms: [{ room_type: 'single', count: 140, rate: 159, breakfast_included: true }, { room_type: 'double', count: 20, rate: 189, breakfast_included: true }], attrition_percent: 15 },
    stats: { lead_time_days: 90, persons_total: 180, rooms_nights_total: 480, peak_day_persons: 180, generated_at: '2025-08-15T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-12', persons: 180 }, { date: '2025-11-13', persons: 170 }, { date: '2025-11-14', persons: 150 }] } },
  },
  {
    name: 'Leadership Workshop',
    venueIndex: 0,
    event: { eventType: 'Training', eventName: 'Leadership Workshop', guests: 15, agenda: 'Interactive leadership training with coach', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 2, need_housing: true, housing_need_count: 15, single_rooms_count: 15, need_activity: false, dates_flexible: true, eventFormat: 'training', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 30, teardown_minutes: 20, confidentiality: 'restricted', languages: ['de'], channel: 'email' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 4800, tax_inclusive: true, category_caps: { fnb_max: 2200 } },
    companyInfo: { organizer: { first_name: 'Julia', last_name: 'Braun', email: 'julia@consult.de', phone: '+49 30 5555 1234', company_name: 'Braun Consulting' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 20, dispositions: ['u-shape'], natural_light: true, seating: 'u-shape', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.2, floor_area_sqm: 45, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 2 } },
    fnb: { abstract: 'Coffee breaks + working lunch', service_style: 'plated', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 3, gluten_free: 1 }, items: ['li_coffee', 'li_lunch', 'li_pm'] },
    equipment: { name: 'Flipchart', model: 'Standard', quantity: 3, connectors: [], operator_required: false, rental_type: 'in-house', catalog_id: 'res-flip' },
    datetime: { from_date: '2025-09-15', from_hour: '09:00', to_date: '2025-09-15', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-09-15', persons: 15, timezone: 'Europe/Berlin', packages: ['pkg_training'], rooms: ['room_exec'], equipment: ['li_flipchart'], remarks: 'U-shape setup' },
    roomBlock: { arrival_date: '2025-09-15', departure_date: '2025-09-16', cutoff_date: '2025-09-01', currency: 'EUR', rooms: [{ room_type: 'single', count: 15, rate: 135, breakfast_included: true }], attrition_percent: 5 },
    stats: { lead_time_days: 21, persons_total: 15, rooms_nights_total: 15, peak_day_persons: 15, generated_at: '2025-08-25T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-09-15', persons: 15 }] } },
  },
  {
    name: 'Product Launch Press Event',
    venueIndex: 0,
    event: { eventType: 'Meeting', eventName: 'Product Launch Press Event', guests: 60, agenda: 'Press conference + product demo + cocktail', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 2, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: false, eventFormat: 'meeting', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 120, teardown_minutes: 90, confidentiality: 'embargoed', languages: ['en', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 22000, tax_inclusive: true, category_caps: { fnb_max: 8000, av_max: 9000 } },
    companyInfo: { organizer: { first_name: 'Tobias', last_name: 'Klein', email: 'tobias@innovate.de', phone: '+49 30 7777 8888', company_name: 'Innovate AG' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 80, dispositions: ['theater'], natural_light: false, seating: 'theater', time_from: '14:00', time_to: '20:00', ceiling_height_m: 4.0, floor_area_sqm: 150, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 300, hardline_ports: 8 } },
    fnb: { abstract: 'Cocktail reception with canapes', service_style: 'reception', dayparts: ['reception'], dietary_counts: { vegetarian: 10, vegan: 5 }, items: ['li_cocktail', 'li_canapes'] },
    equipment: { name: 'LED Screen Wall', model: '4K LED 6x3m', quantity: 1, power_watts: 3500, connectors: ['HDMI', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-led' },
    datetime: { from_date: '2025-11-05', from_hour: '14:00', to_date: '2025-11-05', to_hour: '20:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-05', persons: 60, timezone: 'Europe/Berlin', packages: [], rooms: ['press_room'], equipment: ['li_led_wall', 'li_audio'], remarks: 'Embargo until 16:00' },
    roomBlock: { arrival_date: '2025-11-05', departure_date: '2025-11-05', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 45, persons_total: 60, rooms_nights_total: 0, peak_day_persons: 60, generated_at: '2025-09-20T14:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-05', persons: 60 }] } },
  },
  {
    name: 'Winter Board Meeting',
    venueIndex: 0,
    event: { eventType: 'Meeting', eventName: 'Winter Board Meeting', guests: 12, agenda: 'Board strategy session', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 2, need_housing: true, housing_need_count: 12, single_rooms_count: 10, need_activity: false, dates_flexible: false, eventFormat: 'meeting', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 30, teardown_minutes: 15, confidentiality: 'restricted', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 8500, tax_inclusive: true, category_caps: { fnb_max: 3500 } },
    companyInfo: { organizer: { first_name: 'Helga', last_name: 'Meier', email: 'helga@globalcorp.com', phone: '+49 30 4444 3333', company_name: 'GlobalCorp' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 16, dispositions: ['boardroom'], natural_light: true, seating: 'boardroom', time_from: '08:30', time_to: '17:00', ceiling_height_m: 3.5, floor_area_sqm: 55, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 12 } },
    fnb: { abstract: 'Premium breakfast + plated lunch + afternoon tea', service_style: 'plated', dayparts: ['breakfast', 'coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 2, gluten_free: 1 }, items: ['li_breakfast_premium', 'li_lunch_plated', 'li_tea'] },
    equipment: { name: 'Video Conference', model: 'Cisco Room Kit Pro', quantity: 1, connectors: ['HDMI', 'USB-C'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-vc' },
    datetime: { from_date: '2025-12-10', from_hour: '08:30', to_date: '2025-12-10', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-12-10', persons: 12, timezone: 'Europe/Berlin', packages: ['pkg_board'], rooms: ['boardroom_a'], equipment: ['li_vc'], remarks: 'Confidential session' },
    roomBlock: { arrival_date: '2025-12-09', departure_date: '2025-12-11', cutoff_date: '2025-11-25', currency: 'EUR', rooms: [{ room_type: 'single', count: 10, rate: 175, breakfast_included: true }, { room_type: 'suite', count: 2, rate: 320, breakfast_included: true }], attrition_percent: 0 },
    stats: { lead_time_days: 60, persons_total: 12, rooms_nights_total: 24, peak_day_persons: 12, generated_at: '2025-10-10T11:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-12-10', persons: 12 }] } },
  },
  {
    name: 'Berlin DevOps Meetup',
    venueIndex: 0,
    event: { eventType: 'Meeting', eventName: 'Berlin DevOps Meetup', guests: 45, agenda: 'Evening meetup: 2 talks + networking', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 1, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 45, teardown_minutes: 30, confidentiality: 'standard', languages: ['en'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 2500, tax_inclusive: true, category_caps: { fnb_max: 1500 } },
    companyInfo: { organizer: { first_name: 'Kai', last_name: 'Tanaka', email: 'kai@devops-berlin.org', phone: '+49 30 1111 2222', company_name: 'DevOps Berlin e.V.' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 60, dispositions: ['theater'], natural_light: false, seating: 'theater', time_from: '18:00', time_to: '21:30', ceiling_height_m: 3.8, floor_area_sqm: 100, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 4 } },
    fnb: { abstract: 'Drinks and finger food', service_style: 'reception', dayparts: ['reception'], dietary_counts: { vegetarian: 8, vegan: 5 }, items: ['li_drinks', 'li_finger_food'] },
    equipment: { name: 'Projector + Sound', model: 'Standard AV', quantity: 1, connectors: ['HDMI'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-std-av' },
    datetime: { from_date: '2025-10-16', from_hour: '18:00', to_date: '2025-10-16', to_hour: '21:30', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-16', persons: 45, timezone: 'Europe/Berlin', packages: [], rooms: ['event_lounge'], equipment: ['li_projector'], remarks: 'Evening event' },
    roomBlock: { arrival_date: '2025-10-16', departure_date: '2025-10-16', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 14, persons_total: 45, rooms_nights_total: 0, peak_day_persons: 45, generated_at: '2025-10-02T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-16', persons: 45 }] } },
  },
  {
    name: 'HR Compliance Training',
    venueIndex: 0,
    event: { eventType: 'Training', eventName: 'HR Compliance Training', guests: 30, agenda: 'Full-day mandatory compliance training', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 3, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'training', status: 'inquiry', timezone: 'Europe/Berlin', setup_minutes: 30, teardown_minutes: 20, confidentiality: 'standard', languages: ['de'], channel: 'email' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 3200, tax_inclusive: true, category_caps: { fnb_max: 1800 } },
    companyInfo: { organizer: { first_name: 'Anna', last_name: 'Schulz', email: 'anna@medigroup.de', phone: '+49 30 6666 7777', company_name: 'MediGroup AG' }, internal_owner: { name: 'Emma Schmidt', email: 'emma@hotel.example' } },
    meetingRoom: { capacity: 40, dispositions: ['classroom'], natural_light: true, seating: 'classroom', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.2, floor_area_sqm: 80, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 2 } },
    fnb: { abstract: 'Full-day catering', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 5, gluten_free: 2 }, items: ['li_coffee', 'li_lunch', 'li_pm'] },
    equipment: { name: 'Projector', model: 'Standard', quantity: 1, connectors: ['HDMI'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-proj' },
    datetime: { from_date: '2025-11-20', from_hour: '09:00', to_date: '2025-11-20', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-20', persons: 30, timezone: 'Europe/Berlin', packages: ['pkg_training'], rooms: ['room_c1'], equipment: ['li_projector'], remarks: '' },
    roomBlock: { arrival_date: '2025-11-20', departure_date: '2025-11-20', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 28, persons_total: 30, rooms_nights_total: 0, peak_day_persons: 30, generated_at: '2025-10-23T08:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-20', persons: 30 }] } },
  },

  // ── Grand Hyatt Munich (venue 1) ── 7 events
  {
    name: 'Bavarian Gala Dinner',
    venueIndex: 1,
    event: { eventType: 'Gala', eventName: 'Bavarian Gala Dinner', guests: 220, agenda: 'Black-tie gala with live band and 5-course dinner', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 3, need_housing: true, housing_need_count: 180, single_rooms_count: 140, need_activity: true, dates_flexible: false, eventFormat: 'gala', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 240, teardown_minutes: 180, confidentiality: 'standard', languages: ['de', 'en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 95000, tax_inclusive: true, category_caps: { fnb_max: 55000, av_max: 15000, space_max: 10000, rooms_max: 15000 } },
    companyInfo: { organizer: { first_name: 'Friedrich', last_name: 'von Hohenfeld', email: 'friedrich@autobavaria.de', phone: '+49 89 2345 6789', company_name: 'Auto Bavaria AG' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 280, dispositions: ['banquet'], natural_light: false, seating: 'banquet', time_from: '18:00', time_to: '02:00', ceiling_height_m: 6.0, floor_area_sqm: 600, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 4 } },
    fnb: { abstract: '5-course gala dinner with cocktail reception', service_style: 'plated', dayparts: ['reception', 'dinner'], dietary_counts: { vegetarian: 30, vegan: 15, gluten_free: 10, halal: 8, kosher: 3 }, items: ['li_cocktail_hour', 'li_gala_dinner'] },
    equipment: { name: 'Stage + Lighting', model: 'Gala Package', quantity: 1, power_watts: 8000, connectors: ['DMX', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-gala-pkg' },
    datetime: { from_date: '2025-12-20', from_hour: '18:00', to_date: '2025-12-21', to_hour: '02:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-12-20', persons: 220, timezone: 'Europe/Berlin', packages: ['pkg_gala'], rooms: ['grand_ballroom'], equipment: ['li_stage', 'li_lighting', 'li_audio'], remarks: 'Black-tie dress code' },
    roomBlock: { arrival_date: '2025-12-20', departure_date: '2025-12-22', cutoff_date: '2025-11-30', currency: 'EUR', rooms: [{ room_type: 'single', count: 140, rate: 195, breakfast_included: true }, { room_type: 'double', count: 30, rate: 225, breakfast_included: true }, { room_type: 'suite', count: 10, rate: 450, breakfast_included: true }], attrition_percent: 10 },
    stats: { lead_time_days: 120, persons_total: 220, rooms_nights_total: 360, peak_day_persons: 220, generated_at: '2025-08-22T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-12-20', persons: 220 }] } },
  },
  {
    name: 'EMEA Sales Conference',
    venueIndex: 1,
    event: { eventType: 'Conference', eventName: 'EMEA Sales Conference', guests: 150, agenda: '2-day sales conference with breakout tracks', need_spaces: true, spaces_count: 6, need_catering: true, catering_needs_count: 5, need_housing: true, housing_need_count: 150, single_rooms_count: 130, need_activity: true, dates_flexible: false, eventFormat: 'conference', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 150, teardown_minutes: 90, confidentiality: 'standard', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 62000, tax_inclusive: true, category_caps: { fnb_max: 25000, av_max: 12000, space_max: 8000, rooms_max: 17000 } },
    companyInfo: { organizer: { first_name: 'Sophie', last_name: 'Martin', email: 'sophie@salesforce-emea.com', phone: '+49 89 3456 7890', company_name: 'SalesForce EMEA' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 200, dispositions: ['theater', 'classroom'], natural_light: true, seating: 'theater', time_from: '08:00', time_to: '19:00', ceiling_height_m: 5.0, floor_area_sqm: 350, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 400, hardline_ports: 10 } },
    fnb: { abstract: 'Full-day conference catering for 2 days', service_style: 'buffet', dayparts: ['breakfast', 'coffee_break', 'lunch', 'pm_break', 'dinner'], dietary_counts: { vegetarian: 25, vegan: 10, gluten_free: 8, halal: 3 }, items: ['li_breakfast', 'li_coffee', 'li_lunch', 'li_pm', 'li_dinner'] },
    equipment: { name: 'Full AV Setup', model: 'Conference Pro', quantity: 1, connectors: ['HDMI', 'SDI', 'USB-C'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-conf-av' },
    datetime: { from_date: '2025-10-08', from_hour: '08:00', to_date: '2025-10-09', to_hour: '18:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-08', persons: 150, timezone: 'Europe/Berlin', packages: ['pkg_conf_day'], rooms: ['ballroom_a', 'track_1', 'track_2', 'track_3'], equipment: ['li_av_main', 'li_av_breakout'], remarks: 'Day 1: General session + 3 tracks' },
    roomBlock: { arrival_date: '2025-10-07', departure_date: '2025-10-10', cutoff_date: '2025-09-20', currency: 'EUR', rooms: [{ room_type: 'single', count: 130, rate: 179, breakfast_included: true }, { room_type: 'double', count: 20, rate: 209, breakfast_included: true }], attrition_percent: 12 },
    stats: { lead_time_days: 75, persons_total: 150, rooms_nights_total: 450, peak_day_persons: 150, generated_at: '2025-07-25T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-08', persons: 150 }, { date: '2025-10-09', persons: 145 }] } },
  },
  {
    name: 'Executive Retreat Weekend',
    venueIndex: 1,
    event: { eventType: 'Incentive', eventName: 'Executive Retreat Weekend', guests: 20, agenda: 'Strategy retreat with team building activities', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 4, need_housing: true, housing_need_count: 20, single_rooms_count: 18, need_activity: true, dates_flexible: true, eventFormat: 'incentive', status: 'option', timezone: 'Europe/Berlin', setup_minutes: 60, teardown_minutes: 30, confidentiality: 'restricted', languages: ['en', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 18000, tax_inclusive: true, category_caps: { fnb_max: 8000, rooms_max: 7000 } },
    companyInfo: { organizer: { first_name: 'Lena', last_name: 'Hofmann', email: 'lena@luxbrands.de', phone: '+49 89 4567 8901', company_name: 'Lux Brands GmbH' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 25, dispositions: ['boardroom', 'u-shape'], natural_light: true, seating: 'boardroom', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.5, floor_area_sqm: 60, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 6 } },
    fnb: { abstract: 'Premium F&B with gourmet dinner', service_style: 'plated', dayparts: ['breakfast', 'coffee_break', 'lunch', 'dinner'], dietary_counts: { vegetarian: 4, vegan: 2 }, items: ['li_breakfast_premium', 'li_lunch', 'li_dinner_gourmet'] },
    equipment: { name: 'Wireless Presentation', model: 'ClickShare', quantity: 1, connectors: ['Wireless'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-clickshare' },
    datetime: { from_date: '2025-11-21', from_hour: '09:00', to_date: '2025-11-23', to_hour: '14:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-21', persons: 20, timezone: 'Europe/Berlin', packages: ['pkg_retreat'], rooms: ['exec_suite', 'garden_room'], equipment: ['li_clickshare'], remarks: 'Casual dress code' },
    roomBlock: { arrival_date: '2025-11-21', departure_date: '2025-11-23', cutoff_date: '2025-11-07', currency: 'EUR', rooms: [{ room_type: 'single', count: 18, rate: 210, breakfast_included: true }, { room_type: 'suite', count: 2, rate: 480, breakfast_included: true }], attrition_percent: 0 },
    stats: { lead_time_days: 42, persons_total: 20, rooms_nights_total: 40, peak_day_persons: 20, generated_at: '2025-10-10T15:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-21', persons: 20 }, { date: '2025-11-22', persons: 20 }] } },
  },
  {
    name: 'Pharma Industry Symposium',
    venueIndex: 1,
    event: { eventType: 'Conference', eventName: 'Pharma Industry Symposium', guests: 90, agenda: 'Medical symposium with poster sessions', need_spaces: true, spaces_count: 4, need_catering: true, catering_needs_count: 4, need_housing: true, housing_need_count: 75, single_rooms_count: 75, need_activity: false, dates_flexible: false, eventFormat: 'conference', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 120, teardown_minutes: 60, confidentiality: 'standard', languages: ['en'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 38000, tax_inclusive: true, category_caps: { fnb_max: 16000, av_max: 8000, space_max: 6000, rooms_max: 8000 } },
    companyInfo: { organizer: { first_name: 'Dr. Henrik', last_name: 'Larsen', email: 'henrik@pharmacon.eu', phone: '+49 89 5678 9012', company_name: 'PharmaCon EU' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 120, dispositions: ['theater', 'classroom'], natural_light: true, seating: 'theater', time_from: '08:00', time_to: '18:00', ceiling_height_m: 4.5, floor_area_sqm: 250, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 300, hardline_ports: 8 } },
    fnb: { abstract: '2-day symposium catering with networking dinner', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break', 'dinner'], dietary_counts: { vegetarian: 15, vegan: 5, gluten_free: 4 }, items: ['li_coffee', 'li_lunch', 'li_pm', 'li_dinner_networking'] },
    equipment: { name: 'Poster Boards + AV', model: 'Symposium Kit', quantity: 20, connectors: ['HDMI'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-poster-av' },
    datetime: { from_date: '2025-11-06', from_hour: '08:00', to_date: '2025-11-07', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-06', persons: 90, timezone: 'Europe/Berlin', packages: ['pkg_symposium'], rooms: ['congress_a', 'poster_hall', 'breakout_1', 'breakout_2'], equipment: ['li_av', 'li_poster_boards'], remarks: 'Medical compliance rules apply' },
    roomBlock: { arrival_date: '2025-11-05', departure_date: '2025-11-08', cutoff_date: '2025-10-15', currency: 'EUR', rooms: [{ room_type: 'single', count: 75, rate: 169, breakfast_included: true }], attrition_percent: 10 },
    stats: { lead_time_days: 65, persons_total: 90, rooms_nights_total: 225, peak_day_persons: 90, generated_at: '2025-09-02T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-06', persons: 90 }, { date: '2025-11-07', persons: 85 }] } },
  },
  {
    name: 'Munich Startup Pitch Night',
    venueIndex: 1,
    event: { eventType: 'Meeting', eventName: 'Munich Startup Pitch Night', guests: 80, agenda: '10 startup pitches + investor networking', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 1, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 60, teardown_minutes: 45, confidentiality: 'standard', languages: ['en'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 5500, tax_inclusive: true, category_caps: { fnb_max: 3000, av_max: 1500 } },
    companyInfo: { organizer: { first_name: 'Max', last_name: 'Richter', email: 'max@startupbavaria.de', phone: '+49 89 1111 2222', company_name: 'Startup Bavaria' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 100, dispositions: ['theater'], natural_light: false, seating: 'theater', time_from: '17:00', time_to: '22:00', ceiling_height_m: 4.0, floor_area_sqm: 180, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 4 } },
    fnb: { abstract: 'Standing reception with drinks and bites', service_style: 'reception', dayparts: ['reception'], dietary_counts: { vegetarian: 15, vegan: 8 }, items: ['li_drinks', 'li_bites'] },
    equipment: { name: 'Projector + Timer', model: 'Pitch Setup', quantity: 1, connectors: ['HDMI', 'USB-C'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-pitch' },
    datetime: { from_date: '2025-10-23', from_hour: '17:00', to_date: '2025-10-23', to_hour: '22:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-23', persons: 80, timezone: 'Europe/Berlin', packages: [], rooms: ['innovation_lab'], equipment: ['li_projector', 'li_timer'], remarks: '5 min per pitch' },
    roomBlock: { arrival_date: '2025-10-23', departure_date: '2025-10-23', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 18, persons_total: 80, rooms_nights_total: 0, peak_day_persons: 80, generated_at: '2025-10-05T14:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-23', persons: 80 }] } },
  },
  {
    name: 'Munich Finance Forum',
    venueIndex: 1,
    event: { eventType: 'Conference', eventName: 'Munich Finance Forum', guests: 110, agenda: 'One-day finance roundtable + panel discussions', need_spaces: true, spaces_count: 3, need_catering: true, catering_needs_count: 3, need_housing: true, housing_need_count: 90, single_rooms_count: 90, need_activity: false, dates_flexible: false, eventFormat: 'conference', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 90, teardown_minutes: 60, confidentiality: 'standard', languages: ['en', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 42000, tax_inclusive: true, category_caps: { fnb_max: 18000, av_max: 8000, space_max: 6000, rooms_max: 10000 } },
    companyInfo: { organizer: { first_name: 'Christine', last_name: 'Vogt', email: 'christine@financeeu.org', phone: '+49 89 7654 3210', company_name: 'Finance EU Association' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 140, dispositions: ['theater', 'roundtable'], natural_light: true, seating: 'theater', time_from: '08:00', time_to: '18:00', ceiling_height_m: 4.5, floor_area_sqm: 280, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 300, hardline_ports: 8 } },
    fnb: { abstract: 'Premium day catering + networking lunch', service_style: 'plated', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 18, vegan: 8, gluten_free: 5, halal: 3 }, items: ['li_coffee_premium', 'li_lunch_plated', 'li_pm_premium'] },
    equipment: { name: 'Panel AV Setup', model: 'Forum Package', quantity: 1, connectors: ['HDMI', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-forum-av' },
    datetime: { from_date: '2025-09-25', from_hour: '08:00', to_date: '2025-09-25', to_hour: '18:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-09-25', persons: 110, timezone: 'Europe/Berlin', packages: ['pkg_forum'], rooms: ['conference_1', 'panel_room', 'vip_lounge'], equipment: ['li_av_forum'], remarks: 'VIP speakers require separate green room' },
    roomBlock: { arrival_date: '2025-09-24', departure_date: '2025-09-26', cutoff_date: '2025-09-10', currency: 'EUR', rooms: [{ room_type: 'single', count: 90, rate: 185, breakfast_included: true }], attrition_percent: 8 },
    stats: { lead_time_days: 55, persons_total: 110, rooms_nights_total: 180, peak_day_persons: 110, generated_at: '2025-08-01T11:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-09-25', persons: 110 }] } },
  },
  {
    name: 'Automotive Design Awards',
    venueIndex: 1,
    event: { eventType: 'Gala', eventName: 'Automotive Design Awards', guests: 300, agenda: 'Awards ceremony + dinner + after-party', need_spaces: true, spaces_count: 3, need_catering: true, catering_needs_count: 4, need_housing: true, housing_need_count: 250, single_rooms_count: 200, need_activity: true, dates_flexible: false, eventFormat: 'gala', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 360, teardown_minutes: 240, confidentiality: 'standard', languages: ['en', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 120000, tax_inclusive: true, category_caps: { fnb_max: 55000, av_max: 25000, space_max: 15000, rooms_max: 25000 } },
    companyInfo: { organizer: { first_name: 'Klaus', last_name: 'Seidel', email: 'klaus@autodesign.de', phone: '+49 89 8888 9999', company_name: 'Auto Design Foundation' }, internal_owner: { name: 'Thomas Bauer', email: 'thomas@grandhyatt.example' } },
    meetingRoom: { capacity: 350, dispositions: ['banquet'], natural_light: false, seating: 'banquet', time_from: '17:00', time_to: '03:00', ceiling_height_m: 7.0, floor_area_sqm: 800, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 6 } },
    fnb: { abstract: 'Cocktail reception + 4-course dinner + open bar', service_style: 'plated', dayparts: ['reception', 'dinner'], dietary_counts: { vegetarian: 45, vegan: 20, gluten_free: 15, halal: 10, kosher: 5 }, items: ['li_cocktail', 'li_gala_dinner', 'li_open_bar'] },
    equipment: { name: 'Full Production Package', model: 'Awards Show', quantity: 1, power_watts: 15000, connectors: ['DMX', 'SDI', 'HDMI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-awards' },
    datetime: { from_date: '2025-11-28', from_hour: '17:00', to_date: '2025-11-29', to_hour: '03:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-28', persons: 300, timezone: 'Europe/Berlin', packages: ['pkg_awards'], rooms: ['grand_ballroom', 'foyer', 'vip_area'], equipment: ['li_stage_full', 'li_lighting_full', 'li_audio_full'], remarks: 'Red carpet entrance required' },
    roomBlock: { arrival_date: '2025-11-28', departure_date: '2025-11-30', cutoff_date: '2025-11-10', currency: 'EUR', rooms: [{ room_type: 'single', count: 200, rate: 199, breakfast_included: true }, { room_type: 'double', count: 40, rate: 239, breakfast_included: true }, { room_type: 'suite', count: 10, rate: 520, breakfast_included: true }], attrition_percent: 10 },
    stats: { lead_time_days: 150, persons_total: 300, rooms_nights_total: 500, peak_day_persons: 300, generated_at: '2025-07-01T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-28', persons: 300 }] } },
  },

  // ── Marriott Hamburg (venue 2) ── 6 events
  {
    name: 'Product Launch Hamburg',
    venueIndex: 2,
    event: { eventType: 'Meeting', eventName: 'Product Launch Hamburg', guests: 75, agenda: 'Product unveiling with press and partners', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 2, need_housing: true, housing_need_count: 50, single_rooms_count: 50, need_activity: false, dates_flexible: false, eventFormat: 'meeting', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 120, teardown_minutes: 90, confidentiality: 'embargoed', languages: ['en', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 28000, tax_inclusive: true, category_caps: { fnb_max: 10000, av_max: 12000 } },
    companyInfo: { organizer: { first_name: 'Nils', last_name: 'Hansen', email: 'nils@nordictech.com', phone: '+49 40 1234 5678', company_name: 'Nordic Tech' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 100, dispositions: ['theater'], natural_light: false, seating: 'theater', time_from: '13:00', time_to: '20:00', ceiling_height_m: 4.5, floor_area_sqm: 200, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 300, hardline_ports: 8 } },
    fnb: { abstract: 'Cocktail reception after launch', service_style: 'reception', dayparts: ['reception'], dietary_counts: { vegetarian: 12, vegan: 5 }, items: ['li_cocktail', 'li_canapes_premium'] },
    equipment: { name: 'LED Wall + Sound', model: 'Launch Package', quantity: 1, power_watts: 5000, connectors: ['HDMI', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-launch' },
    datetime: { from_date: '2025-10-15', from_hour: '13:00', to_date: '2025-10-15', to_hour: '20:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-15', persons: 75, timezone: 'Europe/Berlin', packages: [], rooms: ['launch_hall', 'demo_room'], equipment: ['li_led', 'li_sound'], remarks: 'Embargo until 15:00' },
    roomBlock: { arrival_date: '2025-10-14', departure_date: '2025-10-16', cutoff_date: '2025-09-30', currency: 'EUR', rooms: [{ room_type: 'single', count: 50, rate: 155, breakfast_included: true }], attrition_percent: 10 },
    stats: { lead_time_days: 40, persons_total: 75, rooms_nights_total: 100, peak_day_persons: 75, generated_at: '2025-09-05T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-15', persons: 75 }] } },
  },
  {
    name: 'Team Offsite: Engineering',
    venueIndex: 2,
    event: { eventType: 'Incentive', eventName: 'Team Offsite: Engineering', guests: 35, agenda: '2-day offsite with workshops and team dinner', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 4, need_housing: true, housing_need_count: 35, single_rooms_count: 35, need_activity: true, dates_flexible: true, eventFormat: 'incentive', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 45, teardown_minutes: 30, confidentiality: 'standard', languages: ['en'], channel: 'email' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 16000, tax_inclusive: true, category_caps: { fnb_max: 7000, rooms_max: 6000 } },
    companyInfo: { organizer: { first_name: 'Oliver', last_name: 'Berger', email: 'oliver@cloudops.io', phone: '+49 40 2345 6789', company_name: 'CloudOps GmbH' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 40, dispositions: ['u-shape', 'classroom'], natural_light: true, seating: 'u-shape', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.5, floor_area_sqm: 75, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 4 } },
    fnb: { abstract: 'Full-day catering + team dinner at restaurant', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break', 'dinner'], dietary_counts: { vegetarian: 8, vegan: 4, gluten_free: 2 }, items: ['li_coffee', 'li_lunch', 'li_pm', 'li_team_dinner'] },
    equipment: { name: 'Workshop Kit', model: 'Standard', quantity: 4, connectors: ['HDMI'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-workshop' },
    datetime: { from_date: '2025-11-03', from_hour: '09:00', to_date: '2025-11-04', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-03', persons: 35, timezone: 'Europe/Berlin', packages: ['pkg_offsite'], rooms: ['workshop_a', 'workshop_b'], equipment: ['li_kit'], remarks: 'Team building activity on Day 2 afternoon' },
    roomBlock: { arrival_date: '2025-11-02', departure_date: '2025-11-05', cutoff_date: '2025-10-20', currency: 'EUR', rooms: [{ room_type: 'single', count: 35, rate: 145, breakfast_included: true }], attrition_percent: 5 },
    stats: { lead_time_days: 30, persons_total: 35, rooms_nights_total: 105, peak_day_persons: 35, generated_at: '2025-10-04T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-03', persons: 35 }, { date: '2025-11-04', persons: 35 }] } },
  },
  {
    name: 'Maritime Industry Conference',
    venueIndex: 2,
    event: { eventType: 'Conference', eventName: 'Maritime Industry Conference', guests: 200, agenda: '3-day conference on shipping and logistics', need_spaces: true, spaces_count: 5, need_catering: true, catering_needs_count: 6, need_housing: true, housing_need_count: 180, single_rooms_count: 160, need_activity: false, dates_flexible: false, eventFormat: 'conference', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 180, teardown_minutes: 120, confidentiality: 'standard', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 72000, tax_inclusive: true, category_caps: { fnb_max: 30000, av_max: 14000, space_max: 10000, rooms_max: 18000 } },
    companyInfo: { organizer: { first_name: 'Ingrid', last_name: 'Petersen', email: 'ingrid@maritime-eu.org', phone: '+49 40 3456 7890', company_name: 'Maritime EU Forum' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 280, dispositions: ['theater', 'classroom'], natural_light: true, seating: 'theater', time_from: '08:00', time_to: '19:00', ceiling_height_m: 5.5, floor_area_sqm: 450, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 500, hardline_ports: 12 } },
    fnb: { abstract: '3-day conference catering with gala dinner', service_style: 'buffet', dayparts: ['breakfast', 'coffee_break', 'lunch', 'pm_break', 'dinner'], dietary_counts: { vegetarian: 30, vegan: 10, gluten_free: 8, halal: 5 }, items: ['li_breakfast', 'li_coffee', 'li_lunch', 'li_pm', 'li_dinner'] },
    equipment: { name: 'Conference AV + Translation', model: 'Full Setup', quantity: 1, connectors: ['HDMI', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-conf-full' },
    datetime: { from_date: '2025-09-17', from_hour: '08:00', to_date: '2025-09-19', to_hour: '16:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-09-17', persons: 200, timezone: 'Europe/Berlin', packages: ['pkg_maritime'], rooms: ['harbor_hall', 'track_a', 'track_b', 'expo_area'], equipment: ['li_av_main', 'li_translation'], remarks: 'Simultaneous translation EN/DE' },
    roomBlock: { arrival_date: '2025-09-16', departure_date: '2025-09-20', cutoff_date: '2025-08-25', currency: 'EUR', rooms: [{ room_type: 'single', count: 160, rate: 165, breakfast_included: true }, { room_type: 'double', count: 20, rate: 195, breakfast_included: true }], attrition_percent: 12 },
    stats: { lead_time_days: 100, persons_total: 200, rooms_nights_total: 720, peak_day_persons: 200, generated_at: '2025-06-10T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-09-17', persons: 200 }, { date: '2025-09-18', persons: 190 }, { date: '2025-09-19', persons: 165 }] } },
  },
  {
    name: 'Client Advisory Board Q3',
    venueIndex: 2,
    event: { eventType: 'Meeting', eventName: 'Client Advisory Board Q3', guests: 18, agenda: 'Quarterly advisory board meeting', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 2, need_housing: true, housing_need_count: 18, single_rooms_count: 16, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'option', timezone: 'Europe/Berlin', setup_minutes: 30, teardown_minutes: 15, confidentiality: 'restricted', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 9500, tax_inclusive: true, category_caps: { fnb_max: 4000, rooms_max: 4000 } },
    companyInfo: { organizer: { first_name: 'David', last_name: 'Chen', email: 'david@globalfinance.com', phone: '+49 40 4567 8901', company_name: 'Global Finance Corp' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 20, dispositions: ['boardroom'], natural_light: true, seating: 'boardroom', time_from: '09:00', time_to: '16:00', ceiling_height_m: 3.2, floor_area_sqm: 50, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 10 } },
    fnb: { abstract: 'Premium boardroom catering', service_style: 'plated', dayparts: ['coffee_break', 'lunch'], dietary_counts: { vegetarian: 3, gluten_free: 2 }, items: ['li_coffee_premium', 'li_lunch_plated'] },
    equipment: { name: 'Video Conferencing', model: 'Poly Studio X50', quantity: 1, connectors: ['HDMI', 'USB-C'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-vc-poly' },
    datetime: { from_date: '2025-09-30', from_hour: '09:00', to_date: '2025-09-30', to_hour: '16:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-09-30', persons: 18, timezone: 'Europe/Berlin', packages: ['pkg_board'], rooms: ['boardroom_harbor'], equipment: ['li_vc'], remarks: 'NDA required for all attendees' },
    roomBlock: { arrival_date: '2025-09-29', departure_date: '2025-10-01', cutoff_date: '2025-09-15', currency: 'EUR', rooms: [{ room_type: 'single', count: 16, rate: 165, breakfast_included: true }, { room_type: 'suite', count: 2, rate: 350, breakfast_included: true }], attrition_percent: 0 },
    stats: { lead_time_days: 25, persons_total: 18, rooms_nights_total: 36, peak_day_persons: 18, generated_at: '2025-09-05T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-09-30', persons: 18 }] } },
  },
  {
    name: 'Port Authority Workshop',
    venueIndex: 2,
    event: { eventType: 'Training', eventName: 'Port Authority Workshop', guests: 40, agenda: 'Safety & compliance workshop for port staff', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 3, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'training', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 45, teardown_minutes: 30, confidentiality: 'standard', languages: ['de'], channel: 'email' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 5200, tax_inclusive: true, category_caps: { fnb_max: 2800 } },
    companyInfo: { organizer: { first_name: 'Werner', last_name: 'Brandt', email: 'werner@port-hamburg.de', phone: '+49 40 5678 9012', company_name: 'Hamburg Port Authority' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 50, dispositions: ['classroom'], natural_light: true, seating: 'classroom', time_from: '08:30', time_to: '16:30', ceiling_height_m: 3.5, floor_area_sqm: 90, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 2 } },
    fnb: { abstract: 'Full-day training catering', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 6, gluten_free: 2 }, items: ['li_coffee', 'li_lunch', 'li_pm'] },
    equipment: { name: 'Projector + Whiteboard', model: 'Training Kit', quantity: 2, connectors: ['HDMI', 'VGA'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-training' },
    datetime: { from_date: '2025-10-22', from_hour: '08:30', to_date: '2025-10-22', to_hour: '16:30', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-22', persons: 40, timezone: 'Europe/Berlin', packages: ['pkg_training'], rooms: ['training_a', 'practice_room'], equipment: ['li_projector', 'li_whiteboard'], remarks: 'Safety equipment demo space needed' },
    roomBlock: { arrival_date: '2025-10-22', departure_date: '2025-10-22', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 21, persons_total: 40, rooms_nights_total: 0, peak_day_persons: 40, generated_at: '2025-10-01T08:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-22', persons: 40 }] } },
  },
  {
    name: 'Hamburg Harbor Networking',
    venueIndex: 2,
    event: { eventType: 'Meeting', eventName: 'Hamburg Harbor Networking', guests: 100, agenda: 'Industry networking event at harbor-view venue', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 1, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'inquiry', timezone: 'Europe/Berlin', setup_minutes: 60, teardown_minutes: 45, confidentiality: 'standard', languages: ['en', 'de'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 7500, tax_inclusive: true, category_caps: { fnb_max: 5500 } },
    companyInfo: { organizer: { first_name: 'Lisa', last_name: 'Andersen', email: 'lisa@harbornetwork.de', phone: '+49 40 6789 0123', company_name: 'Harbor Network e.V.' }, internal_owner: { name: 'Sarah Fischer', email: 'sarah@marriott-hh.example' } },
    meetingRoom: { capacity: 120, dispositions: ['reception'], natural_light: true, seating: 'reception', time_from: '17:00', time_to: '22:00', ceiling_height_m: 4.0, floor_area_sqm: 200, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 2 } },
    fnb: { abstract: 'Standing reception with harbor-themed menu', service_style: 'reception', dayparts: ['reception'], dietary_counts: { vegetarian: 15, vegan: 8, gluten_free: 5 }, items: ['li_reception_premium'] },
    equipment: { name: 'Background Music', model: 'Wireless Speaker Set', quantity: 4, connectors: ['Bluetooth'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-speakers' },
    datetime: { from_date: '2025-11-13', from_hour: '17:00', to_date: '2025-11-13', to_hour: '22:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-13', persons: 100, timezone: 'Europe/Berlin', packages: [], rooms: ['harbor_lounge'], equipment: ['li_speakers'], remarks: 'Harbor-view terrace if weather permits' },
    roomBlock: { arrival_date: '2025-11-13', departure_date: '2025-11-13', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 15, persons_total: 100, rooms_nights_total: 0, peak_day_persons: 100, generated_at: '2025-10-29T14:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-13', persons: 100 }] } },
  },

  // ── Radisson Blu Frankfurt (venue 3) ── 5 events
  {
    name: 'Annual Banking Summit',
    venueIndex: 3,
    event: { eventType: 'Conference', eventName: 'Annual Banking Summit', guests: 250, agenda: '2-day summit on digital banking and fintech', need_spaces: true, spaces_count: 6, need_catering: true, catering_needs_count: 6, need_housing: true, housing_need_count: 220, single_rooms_count: 200, need_activity: false, dates_flexible: false, eventFormat: 'conference', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 240, teardown_minutes: 150, confidentiality: 'standard', languages: ['en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 85000, tax_inclusive: true, category_caps: { fnb_max: 35000, av_max: 18000, space_max: 12000, rooms_max: 20000 } },
    companyInfo: { organizer: { first_name: 'Elena', last_name: 'Rossi', email: 'elena@bankingsummit.eu', phone: '+49 69 1234 5678', company_name: 'EU Banking Forum' }, internal_owner: { name: 'Michael Wagner', email: 'michael@radisson-fra.example' } },
    meetingRoom: { capacity: 300, dispositions: ['theater', 'classroom'], natural_light: true, seating: 'theater', time_from: '07:30', time_to: '20:00', ceiling_height_m: 6.0, floor_area_sqm: 500, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 500, hardline_ports: 16 } },
    fnb: { abstract: '2-day premium conference catering with gala dinner', service_style: 'buffet', dayparts: ['breakfast', 'coffee_break', 'lunch', 'pm_break', 'dinner', 'reception'], dietary_counts: { vegetarian: 40, vegan: 18, gluten_free: 12, halal: 8, kosher: 5 }, items: ['li_breakfast', 'li_coffee', 'li_lunch', 'li_pm', 'li_gala_dinner', 'li_reception'] },
    equipment: { name: 'Full AV + Streaming', model: 'Summit Package', quantity: 1, power_watts: 12000, connectors: ['HDMI', 'SDI', 'NDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-summit-av' },
    datetime: { from_date: '2025-10-01', from_hour: '07:30', to_date: '2025-10-02', to_hour: '18:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-01', persons: 250, timezone: 'Europe/Berlin', packages: ['pkg_summit'], rooms: ['congress_hall', 'fintech_track', 'digital_track', 'workshop_1', 'workshop_2', 'expo'], equipment: ['li_av_full', 'li_streaming'], remarks: 'Live-streamed keynotes' },
    roomBlock: { arrival_date: '2025-09-30', departure_date: '2025-10-03', cutoff_date: '2025-09-15', currency: 'EUR', rooms: [{ room_type: 'single', count: 200, rate: 175, breakfast_included: true }, { room_type: 'double', count: 15, rate: 205, breakfast_included: true }, { room_type: 'suite', count: 5, rate: 380, breakfast_included: true }], attrition_percent: 12 },
    stats: { lead_time_days: 110, persons_total: 250, rooms_nights_total: 660, peak_day_persons: 250, generated_at: '2025-06-12T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-01', persons: 250 }, { date: '2025-10-02', persons: 235 }] } },
  },
  {
    name: 'Compliance Officers Training',
    venueIndex: 3,
    event: { eventType: 'Training', eventName: 'Compliance Officers Training', guests: 25, agenda: 'Regulatory compliance certification program', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 3, need_housing: true, housing_need_count: 25, single_rooms_count: 25, need_activity: false, dates_flexible: true, eventFormat: 'training', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 30, teardown_minutes: 20, confidentiality: 'restricted', languages: ['en'], channel: 'email' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 12000, tax_inclusive: true, category_caps: { fnb_max: 4500, rooms_max: 5000 } },
    companyInfo: { organizer: { first_name: 'Markus', last_name: 'Becker', email: 'markus@compliance-eu.org', phone: '+49 69 2345 6789', company_name: 'EU Compliance Institute' }, internal_owner: { name: 'Michael Wagner', email: 'michael@radisson-fra.example' } },
    meetingRoom: { capacity: 30, dispositions: ['classroom'], natural_light: true, seating: 'classroom', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.2, floor_area_sqm: 60, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 4 } },
    fnb: { abstract: '2-day training catering', service_style: 'buffet', dayparts: ['coffee_break', 'lunch', 'pm_break'], dietary_counts: { vegetarian: 4, gluten_free: 2 }, items: ['li_coffee', 'li_lunch', 'li_pm'] },
    equipment: { name: 'Projector + Laser Pointer', model: 'Training Standard', quantity: 1, connectors: ['HDMI', 'VGA'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-training-std' },
    datetime: { from_date: '2025-11-10', from_hour: '09:00', to_date: '2025-11-11', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-11-10', persons: 25, timezone: 'Europe/Berlin', packages: ['pkg_cert'], rooms: ['training_room_1'], equipment: ['li_projector'], remarks: 'Certification exam on Day 2 PM' },
    roomBlock: { arrival_date: '2025-11-09', departure_date: '2025-11-12', cutoff_date: '2025-10-25', currency: 'EUR', rooms: [{ room_type: 'single', count: 25, rate: 149, breakfast_included: true }], attrition_percent: 5 },
    stats: { lead_time_days: 35, persons_total: 25, rooms_nights_total: 75, peak_day_persons: 25, generated_at: '2025-10-06T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-11-10', persons: 25 }, { date: '2025-11-11', persons: 25 }] } },
  },
  {
    name: 'FinTech Demo Day',
    venueIndex: 3,
    event: { eventType: 'Meeting', eventName: 'FinTech Demo Day', guests: 120, agenda: 'Startup demos + investor speed dating', need_spaces: true, spaces_count: 3, need_catering: true, catering_needs_count: 2, need_housing: false, housing_need_count: 0, single_rooms_count: 0, need_activity: false, dates_flexible: true, eventFormat: 'meeting', status: 'tentative', timezone: 'Europe/Berlin', setup_minutes: 90, teardown_minutes: 60, confidentiality: 'standard', languages: ['en'], channel: 'widget' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 15000, tax_inclusive: true, category_caps: { fnb_max: 8000, av_max: 5000 } },
    companyInfo: { organizer: { first_name: 'Anja', last_name: 'Schwarz', email: 'anja@fintechfrankfurt.de', phone: '+49 69 3456 7890', company_name: 'FinTech Frankfurt' }, internal_owner: { name: 'Michael Wagner', email: 'michael@radisson-fra.example' } },
    meetingRoom: { capacity: 150, dispositions: ['theater', 'reception'], natural_light: true, seating: 'theater', time_from: '13:00', time_to: '21:00', ceiling_height_m: 4.5, floor_area_sqm: 260, divisible: true, pillars: false, network: { dedicated_bandwidth_mbps: 300, hardline_ports: 8 } },
    fnb: { abstract: 'Lunch + evening networking reception', service_style: 'reception', dayparts: ['lunch', 'reception'], dietary_counts: { vegetarian: 20, vegan: 10, gluten_free: 5 }, items: ['li_lunch_stations', 'li_reception_drinks'] },
    equipment: { name: 'Demo Stations + Stage', model: 'Demo Day Kit', quantity: 12, connectors: ['HDMI', 'USB-C'], operator_required: false, rental_type: 'in-house', catalog_id: 'res-demo-kit' },
    datetime: { from_date: '2025-10-28', from_hour: '13:00', to_date: '2025-10-28', to_hour: '21:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-10-28', persons: 120, timezone: 'Europe/Berlin', packages: [], rooms: ['main_stage', 'demo_hall', 'investor_lounge'], equipment: ['li_demo_stations', 'li_stage_av'], remarks: '12 demo stations needed' },
    roomBlock: { arrival_date: '2025-10-28', departure_date: '2025-10-28', cutoff_date: null, currency: 'EUR', rooms: [], attrition_percent: 0 },
    stats: { lead_time_days: 22, persons_total: 120, rooms_nights_total: 0, peak_day_persons: 120, generated_at: '2025-10-06T11:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-10-28', persons: 120 }] } },
  },
  {
    name: 'EU Regulatory Roundtable',
    venueIndex: 3,
    event: { eventType: 'Meeting', eventName: 'EU Regulatory Roundtable', guests: 30, agenda: 'Closed-door regulatory discussion with EU officials', need_spaces: true, spaces_count: 1, need_catering: true, catering_needs_count: 2, need_housing: true, housing_need_count: 28, single_rooms_count: 25, need_activity: false, dates_flexible: false, eventFormat: 'meeting', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 45, teardown_minutes: 20, confidentiality: 'restricted', languages: ['en', 'fr', 'de'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 14000, tax_inclusive: true, category_caps: { fnb_max: 5000, rooms_max: 6000 } },
    companyInfo: { organizer: { first_name: 'Pierre', last_name: 'Dumont', email: 'pierre@euregulatory.eu', phone: '+49 69 4567 8901', company_name: 'EU Regulatory Council' }, internal_owner: { name: 'Michael Wagner', email: 'michael@radisson-fra.example' } },
    meetingRoom: { capacity: 35, dispositions: ['roundtable'], natural_light: true, seating: 'roundtable', time_from: '09:00', time_to: '17:00', ceiling_height_m: 3.5, floor_area_sqm: 70, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 200, hardline_ports: 10 } },
    fnb: { abstract: 'Premium boardroom catering with working lunch', service_style: 'plated', dayparts: ['coffee_break', 'lunch'], dietary_counts: { vegetarian: 5, halal: 3, kosher: 2 }, items: ['li_coffee_premium', 'li_lunch_plated'] },
    equipment: { name: 'Translation System', model: '3-Channel', quantity: 1, connectors: [], operator_required: true, rental_type: 'third-party', catalog_id: 'res-translation' },
    datetime: { from_date: '2025-12-03', from_hour: '09:00', to_date: '2025-12-03', to_hour: '17:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-12-03', persons: 30, timezone: 'Europe/Berlin', packages: ['pkg_roundtable'], rooms: ['diplomat_room'], equipment: ['li_translation_3ch'], remarks: 'Simultaneous translation EN/FR/DE' },
    roomBlock: { arrival_date: '2025-12-02', departure_date: '2025-12-04', cutoff_date: '2025-11-18', currency: 'EUR', rooms: [{ room_type: 'single', count: 25, rate: 169, breakfast_included: true }, { room_type: 'suite', count: 3, rate: 390, breakfast_included: true }], attrition_percent: 0 },
    stats: { lead_time_days: 50, persons_total: 30, rooms_nights_total: 56, peak_day_persons: 30, generated_at: '2025-10-14T10:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-12-03', persons: 30 }] } },
  },
  {
    name: 'Frankfurt New Year Gala',
    venueIndex: 3,
    event: { eventType: 'Gala', eventName: 'Frankfurt New Year Gala', guests: 180, agenda: 'New Year celebration with dinner, live music, countdown', need_spaces: true, spaces_count: 2, need_catering: true, catering_needs_count: 3, need_housing: true, housing_need_count: 150, single_rooms_count: 100, need_activity: true, dates_flexible: false, eventFormat: 'gala', status: 'contracted', timezone: 'Europe/Berlin', setup_minutes: 300, teardown_minutes: 180, confidentiality: 'standard', languages: ['de', 'en'], channel: 'direct' },
    budget: { budget_defined: true, currency: 'EUR', global_budget: 75000, tax_inclusive: true, category_caps: { fnb_max: 38000, av_max: 12000, space_max: 8000, rooms_max: 17000 } },
    companyInfo: { organizer: { first_name: 'Katarina', last_name: 'Novak', email: 'katarina@frankfurtevents.de', phone: '+49 69 5678 9012', company_name: 'Frankfurt Events GmbH' }, internal_owner: { name: 'Michael Wagner', email: 'michael@radisson-fra.example' } },
    meetingRoom: { capacity: 220, dispositions: ['banquet'], natural_light: false, seating: 'banquet', time_from: '18:00', time_to: '02:00', ceiling_height_m: 5.5, floor_area_sqm: 450, divisible: false, pillars: false, network: { dedicated_bandwidth_mbps: 100, hardline_ports: 4 } },
    fnb: { abstract: 'Champagne reception + 5-course dinner + midnight buffet', service_style: 'plated', dayparts: ['reception', 'dinner'], dietary_counts: { vegetarian: 25, vegan: 12, gluten_free: 8, halal: 5 }, items: ['li_champagne_reception', 'li_gala_dinner', 'li_midnight_buffet'] },
    equipment: { name: 'Entertainment Package', model: 'Gala NYE', quantity: 1, power_watts: 10000, connectors: ['DMX', 'SDI'], operator_required: true, rental_type: 'third-party', catalog_id: 'res-nye-pkg' },
    datetime: { from_date: '2025-12-31', from_hour: '18:00', to_date: '2026-01-01', to_hour: '02:00', timezone: 'Europe/Berlin' },
    conferenceDay: { date: '2025-12-31', persons: 180, timezone: 'Europe/Berlin', packages: ['pkg_nye'], rooms: ['skyline_ballroom', 'cocktail_terrace'], equipment: ['li_stage', 'li_lighting', 'li_dj'], remarks: 'Midnight fireworks viewing from terrace' },
    roomBlock: { arrival_date: '2025-12-31', departure_date: '2026-01-02', cutoff_date: '2025-12-15', currency: 'EUR', rooms: [{ room_type: 'single', count: 100, rate: 199, breakfast_included: true }, { room_type: 'double', count: 40, rate: 249, breakfast_included: true }, { room_type: 'suite', count: 10, rate: 420, breakfast_included: true }], attrition_percent: 5 },
    stats: { lead_time_days: 90, persons_total: 180, rooms_nights_total: 300, peak_day_persons: 180, generated_at: '2025-10-01T09:00:00+02:00', version: 'v1.0', details: { per_day: [{ date: '2025-12-31', persons: 180 }] } },
  },
];

export interface ScenarioPack {
  id: string;
  name: string;
  description: string;
  eventIndices: number[];
}

export const SCENARIO_PACKS: ScenarioPack[] = [
  {
    id: 'all',
    name: 'Full Portfolio',
    description: 'All 25 events across 4 venues',
    eventIndices: TEMPLATES.map((_, i) => i),
  },
  {
    id: 'berlin',
    name: 'Hotel Berlin Mitte',
    description: '7 events: meetings, conferences, trainings',
    eventIndices: TEMPLATES.map((t, i) => (t.venueIndex === 0 ? i : -1)).filter((i) => i >= 0),
  },
  {
    id: 'munich',
    name: 'Grand Hyatt Munich',
    description: '7 events: galas, conferences, retreats',
    eventIndices: TEMPLATES.map((t, i) => (t.venueIndex === 1 ? i : -1)).filter((i) => i >= 0),
  },
  {
    id: 'hamburg',
    name: 'Marriott Hamburg',
    description: '6 events: launches, offsites, conferences',
    eventIndices: TEMPLATES.map((t, i) => (t.venueIndex === 2 ? i : -1)).filter((i) => i >= 0),
  },
  {
    id: 'frankfurt',
    name: 'Radisson Blu Frankfurt',
    description: '5 events: summits, galas, training',
    eventIndices: TEMPLATES.map((t, i) => (t.venueIndex === 3 ? i : -1)).filter((i) => i >= 0),
  },
  {
    id: 'quick',
    name: 'Quick Demo',
    description: '4 events, one per venue',
    eventIndices: [0, 7, 14, 20],
  },
];

export function getEventTemplates(indices: number[]): { name: string; components: Record<string, Record<string, unknown>> }[] {
  return indices.map((idx) => {
    const tpl = TEMPLATES[idx];
    const venue = VENUES[tpl.venueIndex];
    return {
      name: tpl.name,
      components: buildComponents(tpl, venue),
    };
  });
}

export { TEMPLATES };
